### ISSUE TITLE
Is a ban possible?

### ISSUE THREAD

**Issue by Qu1kLyy** [w0nxyApex/Deadlock-Tweaks-config#9]
Can I get banned for this config?

**Comment by w0nxyApex** [comment]
As long as you don't violate Valve's ToS, it shouldn't be an issue. Specifically, reducing the values in the video.txt file shouldn't cause any problems. There was a case in Apex Legends where it was possible, due to a bug, to use commands that made players invisible or removed smoke effects. This is considered cheating, and a streamer who did this on stream was banned. Commands like that don't exist in the .cfg file. I think no one will get banned for what you're doing here, and I also believe it doesn't violate the ToS. However, I can't give you any guarantees.
